### ISSUE TITLE
[KeyError]: construct_result  -> StatusType() missing statuses (cooling system, undertray)

### ISSUE THREAD

**Issue by ibrahimroshdy** [Samuel-Roach/ergast-py#11]
Hi, @Samuel-Roach 

https://github.com/Samuel-Roach/ergast-py/blob/ea4efd92d864e7a1a586a26271263eeaedc2c307/ergast_py/constants/status_type.py#L9

**and**

https://github.com/Samuel-Roach/ergast-py/blob/ea4efd92d864e7a1a586a26271263eeaedc2c307/ergast_py/constants/status_type.py#L153

are both missing two statues which are `Cooling system` and `Undertray` 

---

### Replicate Error
**Pulling results data from the Jeddah, Saudi Arabia Round [2] 2022**
_Valtteri Bottas_ had a status of `Cooling system` with the status id of `141` in Ergast Data

``` python
# Pulling Jeddah, 2022 results (round 2)
import ergast_py

e = ergast_py.Ergast()
e.season(2022).round(2).get_results()
```

<img width="1214" alt="statuestypeerror" src="https://user-images.githubusercontent.com/22573766/221191901-c4690f7d-3d01-41a7-81e8-fb82d719671f.png">

`StatusType()` has statuses from `0` to `139` missing two other statues which are **Cooling system** and **Undertray**

---

### Quick Fix
**Adding missing statuses to properties respectively**

``` python
class StatusType():

    @property
    def string_to_id(self):
        return {
            "": 0,
            "Finished": 1,
            # .....
            "Illness": 139,
            "Undertray": 140, # Added
            "Cooling system": 141 # Added
       }
       
    @property
    def id_to_string(self):
        """
        Return the map of StatusType ids to strings
        """
        return {
            0: "",
            1: "Finished",
            # ....
            139: "Illness",
            140: "Undertray", # Added
            141: "Cooling system" # Added
      }
```

**Comment by Samuel-Roach** [comment]
Thanks for raising this :D Should be fixed as part of #16
