### ISSUE TITLE
New SSL cert on ergast.com breaks ergast-py

### ISSUE THREAD

**Issue by y34hbuddy** [Samuel-Roach/ergast-py#23]
Hi Samuel, looks like the SSL certificates on ergast.com were updated recently but they are missing the intermediate CA cert, so Python `requests` is failing to connect.

One solution is to simply wait (and hope) the admin at ergast.com fixes the SSL chain issue. Another would be to manually set the CA cert bundle in code, but this is far from ideal.

**Comment by y34hbuddy** [comment]
Appears ergast.com's admin has resolved the issue!

**Comment by Samuel-Roach** [comment]
Thanks for chasing this @y34hbuddy (:
