### ISSUE TITLE
New release please!

### ISSUE THREAD

**Issue by y34hbuddy** [Samuel-Roach/ergast-py#27]
Hi Samuel,

Can you please release an updated version of this package to PyPI? There is a bugfix in your main branch (namely this line: https://github.com/Samuel-Roach/ergast-py/blob/bee0358f09d159a246eeefd36888a8f89d1266c0/ergast_py/helpers.py#L19) that is not in the 0.7.0 release, causing issues with my Home Assistant integration.

Cheers!

**Comment by Samuel-Roach** [comment]
Sorry for the delay! Released!

**Comment by y34hbuddy** [comment]
Legend! Cheers, Sam
