### ISSUE TITLE
Error when requesting races that have no start time

### ISSUE THREAD

**Issue by estevE11** [Samuel-Roach/ergast-py#4]
I tried requesting all Alonso races but I get an error which is the following:
![image](https://user-images.githubusercontent.com/15111802/213881237-53dea5c3-b4c5-4856-a962-0c478bbd42c2.png)

Basically:
`ValueError: time data '2001-03-04 ' does not match format '%Y-%m-%d %H:%M:%SZ'`

Looking at the code I saw you have this function which constructs a date-time based on a date and a time:
![image](https://user-images.githubusercontent.com/15111802/213881309-a28fb31f-8adb-470e-9182-35519f2b9d2e.png)

As seen in the error message it happens when the above function gets passed the race time
![image](https://user-images.githubusercontent.com/15111802/213881394-f2e4001b-1444-4199-9823-7c75a40a095e.png)

Looking at the data directly from Ergast API we can see that some old races don't have a race start time
![image](https://user-images.githubusercontent.com/15111802/213881524-555b8459-7148-4864-8534-4f57ea8a7f19.png)
![image](https://user-images.githubusercontent.com/15111802/213881543-05d776c9-92fd-454c-85eb-199b988d63f4.png)

**Comment by Samuel-Roach** [comment]
Resolved in https://github.com/Samuel-Roach/ergast-py/pull/5. Thanks for the contribution :)
